(include "src/utility")
(include "src/storage.scm")

(define-record documentation arguments description)
(define-record command       name implementation documentation)

(define (perform-help arguments)
  (let ((printer (make-kv-printer 0 30)))
    (for-each print (map (lambda (command)
                          (let ((documentation (command-documentation command)))
                            (printer (documentation-arguments   documentation)
                                     (documentation-description documentation))))
                         commands))))

(define (perform-add sources)
  (if (not (null-list? sources))
    (for-each (lambda (source) (print (add-blob (read-all source))))
              sources)
    (print (add-blob (read-all (current-input-port))))))

(define (perform-get hashes)
  (if (not (null-list? hashes))
    (for-each (lambda (hash) (print (get-blob hash)))
              hashes)
    (print #f)))

(define (perform-check hashes)
  (if (not (null-list? hashes))
    (for-each (lambda (hash) (print (blob-exists? hash)))
              hashes)
    (print #f)))
